# Generated by Django 4.1.3 on 2022-12-01 07:16

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='№ Зачётной книжки')),
                ('name', models.CharField(max_length=255, verbose_name='Фамилия и имя')),
                ('password', models.TextField(verbose_name='Пароль')),
                ('uuid', models.TextField(null=True, verbose_name='UUID текущей сессии')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Вопрос')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Картинка к вопросу')),
                ('time', models.IntegerField(validators=[django.core.validators.MinValueValidator(5)], verbose_name='Время в секундах')),
                ('level', models.CharField(choices=[('EASY', 'Лёгкий'), ('MEDIUM', 'Средний'), ('HARD', 'Сложный')], max_length=10, verbose_name='Сложность')),
                ('type', models.CharField(choices=[('TEXT', 'Текстовый'), ('OPTION', 'Вариативный')], max_length=15, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название раздела')),
            ],
            options={
                'verbose_name': 'Раздел',
                'verbose_name_plural': 'Разделы',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('THEORY', 'Теория'), ('METHODOLOGY', 'Методология'), ('LEARNING_PROBLEM', 'Учебные проблемы')], max_length=20)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(verbose_name='Время начала')),
                ('time_end', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euk.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euk.customuser', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Тест пользователя',
                'verbose_name_plural': 'Тесты пользователя',
            },
        ),
        migrations.CreateModel(
            name='OptionQuestion',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='option_question', serialize=False, to='euk.question')),
                ('variant_1', models.CharField(max_length=255, verbose_name='Вариант №1')),
                ('variant_2', models.CharField(max_length=255, verbose_name='Вариант №2')),
                ('variant_3', models.CharField(max_length=255, verbose_name='Вариант №3')),
                ('variant_4', models.CharField(max_length=255, verbose_name='Вариант №4')),
                ('answer', models.IntegerField(verbose_name='Правильный вариант')),
            ],
            options={
                'verbose_name': 'Вариативный вопрос',
                'verbose_name_plural': 'Вариативные вопросы',
            },
        ),
        migrations.CreateModel(
            name='TextQuestion',
            fields=[
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='text_question', serialize=False, to='euk.question')),
                ('answer', models.TextField(verbose_name='Правильный ответ')),
            ],
            options={
                'verbose_name': 'Текстовый вопрос',
                'verbose_name_plural': 'Текстовые вопросы',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.TextField(null=True, verbose_name='Ответ')),
                ('type', models.CharField(choices=[('TEXT', 'Текстовый'), ('OPTION', 'Вариативный')], max_length=15, verbose_name='Тип вопроса')),
                ('time', models.DateTimeField(verbose_name='Время ответа')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euk.question', verbose_name='Вопрос')),
                ('test_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euk.testuser', verbose_name='Тест пользователя')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователя',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название темы')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euk.section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Тема',
                'verbose_name_plural': 'Темы',
            },
        ),
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euk.topic', verbose_name='Тема'),
        ),
        migrations.AddField(
            model_name='question',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='euk.test', verbose_name='Тест'),
        ),
    ]
